apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.selector }}-service
spec:
  type: NodePort
  selector:
    app: {{ .Values.selector }}
  ports:
    - protocol  : TCP
      port      : {{ .Values.containerPort }}
      targetPort: {{ .Values.containerPort }}
      nodePort  : {{ .Values.nodePort }}